micronaut:
  application:
    name: students
---
micronaut:
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${ACCESS_TOKEN_SECRET}
        generator:
          access-token:
            expiration: 2629746
          refresh-token:
            secret: ${REFRESH_TOKEN_SECRET}
---
netty:
  default:
    allocator:
      max-order: 3
---
datasources:
  default:
    pool-name: he-hikari-pool
    maximum-pool-size: 2
    url: jdbc:mysql://${DATABASE_ENDPOINT}:3306/${DATABASE_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
