micronaut:
  application:
    name: auth
---
micronaut:
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "mqt9hg3bCvBx3TyR.jEz39ewr_LGi*RTFrZAefHV3i"
        generator:
          access-token:
            expiration: 2629746
          refresh-token:
            secret: "@YabzWDPohcUPcLhqCD.X9!UFCqt2_Qf!MHWaJPE8H"
---
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        proc:
          param_null_passing: true
        hbm2ddl:
          auto: none
        show_sql: true
---
jackson:
  serializationInclusion: ALWAYS
---
datasources:
  default:
    pool-name: he-hikari-pool
    maximum-pool-size: 2
    url: jdbc:mysql://localhost:3306/boilerplate
    driverClassName: com.mysql.cj.jdbc.Driver
    username: mysql
    password: mysql
